version: "3.3"
services:
  mysql:
    image: mysql:8.0.32
    restart: "no"
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    expose:
      - '3306'
  redis:
    image: redis:7.2-rc-alpine
    restart: "no"
    command: redis-server --requirepass password
    ports:
      - '6379:6379'
  kafka:
    image: docker.io/bitnami/kafka:3.4
    ports:
      - "9092:9092"
    environment:
      - ALLOW_PLAINTEXT_LISTENER=yes